<a href="https://colab.research.google.com/github/vivekadithya-s/Computational_Linguistics/blob/master/colab_good_cl_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


## **OFFENSIVE WORD DETECTION** 

In [0]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

dafa = pd.read_csv('drive/My Drive/Colab Notebooks/CLData/labeled_data.csv')

#<p>The dataset was used in Proceedings of the 11th International AAAI Conference on Weblogs and Social Media</p>
#The dataset is obtained from this website
#https://data.world/thomasrdavidson/hate-speech-and-offensive-language

#<p>Every tweet in this dataset is marked either as hate_speech, offensive_lanuage or neither</p>

#We have considered hate_speech and offensive_language as one category and neither as another category

#dafa.head(5)

dafa = dafa.drop('count', axis = 1)

dafa = dafa.drop('hate_speech', axis = 1)

dafa = dafa.drop('offensive_language', axis = 1)

dafa = dafa.drop('neither', axis = 1)



dafa = dafa.drop(dafa.columns[0], axis = 1)

#dafa.head(5)

y = dafa['class']

dafa = dafa.drop('class', axis = 1)

#dafa.head(5)

#dafa = dafa = dafa.drop('neither', axis = 1)

#y.head(5)

y = y.replace(to_replace = 1, value = 0)

y = y.replace(to_replace = 2, value = 1)

#dafa = dafa.drop('class', axis = 1)

df = dafa

X_train, X_test, y_train, y_test = train_test_split(df['tweet'], y, test_size=0.33, random_state=42)


count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)
count_test = count_vectorizer.transform(X_test)

tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)
tfidf_train = tfidf_vectorizer.fit_transform(X_train)
tfidf_test = tfidf_vectorizer.transform(X_test)

tfidf_vectorizer.get_feature_names()[-10:]
count_vectorizer.get_feature_names()[:10]

count_df = pd.DataFrame(count_train.A, columns=count_vectorizer.get_feature_names())
tfidf_df = pd.DataFrame(tfidf_train.A, columns=tfidf_vectorizer.get_feature_names())
difference = set(count_df.columns) - set(tfidf_df.columns)

#print(count_df.equals(tfidf_df))
count_df.head()

tfidf_df.head()

#clf = MultinomialNB()
clf = PassiveAggressiveClassifier()
clf.fit(tfidf_train, y_train)
pred = clf.predict(tfidf_test)
score = metrics.accuracy_score(y_test, pred)
score = score * 100
print("Offensive word detection accuracy using PAC:   %0.3f" % score)

#y_test.head(5)

#pred

c = 0
for i in pred:
    if(i==1):
        c+=1
#print(c)

c = 0
for i in pred:
    if(i==0):
        c+=1
#print(c)

cm = metrics.confusion_matrix(y_test, pred, labels=[0, 1])
print(cm)

Offensive word detection accuracy using PAC:   94.669
[[6607  193]
 [ 243 1136]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.passive_aggressive.PassiveAggressiveClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


In [0]:
clf = MultinomialNB()
clf.fit(tfidf_train, y_train)
pred = clf.predict(tfidf_test)
score = metrics.accuracy_score(y_test, pred)
score = score * 100
print("Offensive word detection accuracy using MNB:   %0.3f" % score)

#y_test.head(5)

#pred

c = 0
for i in pred:
    if(i==1):
        c+=1
#print(c)

c = 0
for i in pred:
    if(i==0):
        c+=1
#print(c)

cm = metrics.confusion_matrix(y_test, pred, labels=[0, 1])
print(cm)

Offensive word detection accuracy using MNB:   84.705
[[6796    4]
 [1247  132]]


# FAKE NEWS DETECTION

In [0]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

df = pd.read_csv('drive/My Drive/Colab Notebooks/CLData/train.tsv', delimiter='\t')
print(df.shape)

#This is the Liar, Liar pants on Fire dataset by William Yang Wang
#https://arxiv.org/pdf/1705.00648.pdf
#This dataset divides the news into six categories - <b>Half-true, mostly-true, true, barely-true, false, pants-fire</b></p>
#For our project we have reduced the labesl to two - Fake or Real. This means we have combined similar labels.</p> 



new = df[df.columns[1:3]]



new.columns = ['Label', 'news']



new['Label'].unique()

#new['Label'] = new['Label'].replace('half-true','true')
#new['Label'] = new['Label'].replace('mostly-true','true')
#new['Label'] = new['Label'].replace('barely-true','false')
new['Label'] = new['Label'].replace('pants-fire','false')

train = new.copy()



df = pd.read_csv('drive/My Drive/Colab Notebooks/CLData/test.tsv', delimiter='\t')
new2 = df[df.columns[1:3]]
new2.columns = ['Label', 'news']
#new2['Label'] = new2['Label'].replace('half-true','true')
#new2['Label'] = new2['Label'].replace('mostly-true','true')
#new2['Label'] = new2['Label'].replace('barely-true','false')
new2['Label'] = new2['Label'].replace('pants-fire','false')
test = new2.copy()

frames = [train, test]
result = pd.concat(frames, ignore_index=True)

new['Label'].value_counts()

new1 = new[new.Label=='true'].sample(n=1000).copy()
new2 = new[new.Label=='false'].sample(frac=1).copy()
frames = [new1, new2]
result = pd.concat(frames, ignore_index=True)


result['Label'].value_counts()

result = result.sample(frac=1)
df = result

df['Label'].value_counts()



y = df['Label']
df = df.drop('Label', axis = 1)

#df.shape

maxacc=0
for iii in range(1):
    #df = df.sample(frac=1)
    #print(df['Label'].value_counts())

    X_train, X_test, y_train, y_test = train_test_split(df['news'], y, test_size=0.20, random_state=24)
    #iii+=9
    count_vectorizer = CountVectorizer(stop_words='english')
    count_train = count_vectorizer.fit_transform(X_train)
    count_test = count_vectorizer.transform(X_test)

    tfidf_vectorizer = TfidfVectorizer(stop_words='english')
    tfidf_train = tfidf_vectorizer.fit_transform(X_train)
    tfidf_test = tfidf_vectorizer.transform(X_test)

    tfidf_vectorizer.get_feature_names()[-10:]
    count_vectorizer.get_feature_names()[:10]

    count_df = pd.DataFrame(count_train.A, columns=count_vectorizer.get_feature_names())
    tfidf_df = pd.DataFrame(tfidf_train.A, columns=tfidf_vectorizer.get_feature_names())
    difference = set(count_df.columns) - set(tfidf_df.columns)

    #print(count_df.equals(tfidf_df))
    count_df.head()

    tfidf_df.head()

    linear_clf = MultinomialNB()
    #linear_clf = PAC(max_iter=1000)


    linear_clf.fit(tfidf_train, y_train)
    pred = linear_clf.predict(tfidf_test)
    score = metrics.accuracy_score(y_test, pred)
    score = score * 100
    if(score>maxacc):
        maxacc=score
        print("Fake News detection accuracy using MNB:   %0.3f" % score)
        
    cm = metrics.confusion_matrix(y_test, pred, labels=['true', 'false'])

print(cm)



(10239, 14)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:35: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:47: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


Fake News detection accuracy using MNB:   75.359
[[  0 189]
 [  0 578]]


In [0]:
from sklearn.linear_model import PassiveAggressiveClassifier as PAC

for i in range(1):  
    linear_clf = PAC()


    linear_clf.fit(tfidf_train, y_train)
    pred = linear_clf.predict(tfidf_test)
    score = metrics.accuracy_score(y_test, pred)
    score = score * 100
    if(score>0):
        maxacc=score
        print("Fake News detection accuracy using PAC:   %0.3f" % score)
    cm = metrics.confusion_matrix(y_test, pred, labels=['true', 'false'])

print(cm)

Fake News detection accuracy using PAC:   68.970
[[ 57 136]
 [102 472]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.passive_aggressive.PassiveAggressiveClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


# SARCASM DETECTION

In [0]:
#/Users/vivad/Downloads/all/yelp_training_set/yelp_training_set_review.json

In [0]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt





import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

import csv

txt_file1 = b"drive/My Drive/Colab Notebooks/CLData/sarcasm_tweets_gaps.txt"
csv_file1 = b"drive/My Drive/Colab Notebooks/CLData/sarcasm_good.csv"
txt_file2 = b"drive/My Drive/Colab Notebooks/CLData/nonsarcasm_tweets_nogap.txt"
csv_file2 = b"drive/My Drive/Colab Notebooks/CLData/nonsarcasm_good.csv"
in_txt1 = csv.reader(open(txt_file1, "rt", encoding='UTF-8'), delimiter = '\n')
out_csv1 = csv.writer(open(csv_file1, 'wt', encoding='UTF-8'))

out_csv1.writerows(in_txt1)

in_txt2 = csv.reader(open(txt_file2, "rt", encoding='UTF-8'), delimiter = '\n')
out_csv2 = csv.writer(open(csv_file2, 'wt', encoding='UTF-8'))

out_csv2.writerows(in_txt2)

df1 = pd.read_csv('drive/My Drive/Colab Notebooks/CLData/sarcasm_good.csv', header=None)
df2 = pd.read_csv('drive/My Drive/Colab Notebooks/CLData/nonsarcasm_good.csv', header=None)




frames = [df1, df2]
df3 = pd.concat(frames, ignore_index=True)
#print(df3.shape)
df3["label"] =''

df3.shape
for i in range(2303):
    
    df3.at[i,'label']=str('sarcasm')
for i in range(2303, 3655):
    
    df3.at[i,'label']=str('non-sarcasm')
df3 = df3.rename(columns={ df3.columns[0]: "text" })

df3.shape


##

df3 = df3.rename(columns={ df3.columns[0]: "text" })

df = df3.copy()
dfnn = df.copy()
df = df.sample(frac=1).copy()

dforg = df.copy()
#print(df.shape)
#df = df.set_index('Unnamed: 0')
dff = df.copy()
df.head()
y = df.label
#dff = df.drop('title', axis=1)
#dff = df.drop('text', axis=1)
#dff =dff.drop(df.columns[[0,1,2]], axis=1).copy()
#print(dff.head())



df = df.drop('label', axis=1)

# Splitting the dataset into Training and testing
X_train, X_test, y_train, y_test = train_test_split(df['text'], y, test_size=0.33, random_state=2)
count_vectorizer = CountVectorizer(stop_words='english')
X_trainpd = X_train.to_frame(name=None)

count_train = count_vectorizer.fit_transform(X_train)
count_test = count_vectorizer.transform(X_test)

tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)
tfidf_train = tfidf_vectorizer.fit_transform(X_train)
tfidf_test = tfidf_vectorizer.transform(X_test)

tfidf_vectorizer.get_feature_names()[-10:]
count_vectorizer.get_feature_names()[:10]

count_df = pd.DataFrame(count_train.A, columns=count_vectorizer.get_feature_names())
tfidf_df = pd.DataFrame(tfidf_train.A, columns=tfidf_vectorizer.get_feature_names())
difference = set(count_df.columns) - set(tfidf_df.columns)

#print(count_df.equals(tfidf_df))
count_df.head()

tfidf_df.head()

linear_clf = MultinomialNB()
#linear_clf = PAC(max_iter=1000)


linear_clf.fit(count_train, y_train)
pred = linear_clf.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
score = score * 100
print("Sarcasm Detection accuracy using MNB:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred, labels=['sarcasm', 'non-sarcasm'])

print(cm)






Sarcasm Detection accuracy using MNB:   86.764
[[718  62]
 [ 67 357]]


In [0]:
linear_clf = PAC(max_iter=1000)


linear_clf.fit(count_train, y_train)
pred = linear_clf.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
score = score * 100
print("Sarcasm Detection accuracy using PAC:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred, labels=['sarcasm', 'non-sarcasm'])

print(cm)



Sarcasm Detection accuracy using PAC:   82.082
[[718  58]
 [117 299]]


In [0]:
data = dfnn.copy()
data = data.sample(frac=1).copy()
df3["labelnn"] =''

data['labelnn'] = [1 if x == 'sarcasm' else 0 for x in data.label]
from numpy.random import seed
seed(13)
from tensorflow import set_random_seed
set_random_seed(13)

X, y = (data['text'].values, data['labelnn'].values)
tk = Tokenizer(lower = True)
tk.fit_on_texts(X)
X_seq = tk.texts_to_sequences(X)
X_pad = pad_sequences(X_seq, maxlen=25, padding='post')

X_train, X_test, y_train, y_test = train_test_split(X_pad, y, test_size = 0.10)

batch_size = 250
X_train1 = X_train[batch_size:]
y_train1 = y_train[batch_size:]
X_valid = X_train[:batch_size]
y_valid = y_train[:batch_size]


vocabulary_size = len(tk.word_counts.keys())+1
max_words = 25
embedding_size = 32
model = Sequential()
model.add(Embedding(vocabulary_size, embedding_size, input_length=max_words))

model.add(LSTM(50))
model.add(Dense(1, activation='sigmoid'))
adam = Adam(lr=0.0001)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train1, y_train1 , validation_data=(X_valid, y_valid), batch_size=40, epochs=7, verbose=1)

Train on 3128 samples, validate on 250 samples
Epoch 1/7
3128/3128 [==============================] - 17s 5ms/step - loss: 0.6197 - acc: 0.6646 - val_loss: 0.4054 - val_acc: 0.8240
Epoch 2/7
3128/3128 [==============================] - 6s 2ms/step - loss: 0.2284 - acc: 0.9204 - val_loss: 0.2336 - val_acc: 0.9160
Epoch 3/7
3128/3128 [==============================] - 6s 2ms/step - loss: 0.0909 - acc: 0.9763 - val_loss: 0.2633 - val_acc: 0.9200
Epoch 4/7
3128/3128 [==============================] - 6s 2ms/step - loss: 0.0529 - acc: 0.9879 - val_loss: 0.3472 - val_acc: 0.8960
Epoch 5/7
3128/3128 [==============================] - 6s 2ms/step - loss: 0.0312 - acc: 0.9936 - val_loss: 0.3497 - val_acc: 0.9040
Epoch 6/7
3128/3128 [==============================] - 6s 2ms/step - loss: 0.0267 - acc: 0.9930 - val_loss: 0.2937 - val_acc: 0.9000
Epoch 7/7
3128/3128 [==============================] - 6s 2ms/step - loss: 0.0289 - acc: 0.9946 - val_loss: 0.3308 - val_acc: 0.9160


In [0]:
scores = model.evaluate(X_test, y_test, verbose=0)
print("Test Accuracy :"+str(scores[1]*100))

Test Accuracy :90.69148923488373


# SENTIMENT ANALYSIS

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import json
from sklearn.metrics import confusion_matrix, classification_report
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense, Dropout
from sklearn import metrics
from keras.models import Sequential, model_from_json
from sklearn.linear_model import PassiveAggressiveClassifier as PAC
from keras.layers.core import Dropout, Dense, Activation
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import LSTM
from keras.layers.convolutional import Convolution1D, MaxPooling1D
from keras.callbacks import ModelCheckpoint
from keras.callbacks import EarlyStopping
from keras.optimizers import Adam


#df=pd.read_json("drive/My Drive/Colab Notebooks/yelp_training_set_review.json", lines=True)
#print(df)
#df.to_csv("drive/My Drive/Colab Notebooks/final_senti_results.csv")

df = pd.read_csv('drive/My Drive/Colab Notebooks/final_senti_results.csv', index_col=False)
dforg2 = df.copy()
df.shape

df['stars'].unique()

dff =df.drop(df.columns[[0,1,2,3, 6,7,8]], axis=1).copy()

dff.head()


dff['stars'].unique()

len(dff)

dff['stars'].value_counts()

dfpos = dff[dff.stars==5].sample(n=20000)

dfpos.head()
dfpos['stars'].value_counts()

dfneg = dff[dff.stars==1].sample(frac=1)
dfneg['stars'].value_counts()

frames = [dfpos, dfneg]
df3 = pd.concat(frames, ignore_index=True)
df4 = df3.copy()
df3['stars'] = df3['stars'].replace(1,'negative')
df3['stars'] = df3['stars'].replace(5,'positive')

Using TensorFlow backend.


In [0]:
dforg = df3.copy()
#df3['stars'] = df3['stars'].replace(1,'negative')
#df3['stars'] = df3['stars'].replace(5,'positive')
df = df3.copy()
df = df.sample(n=20000).copy()

#print(df.shape)
#df = df.set_index('Unnamed: 0')
dff = df.copy()
#print(df.head())
y = df.stars
#dff = df.drop('title', axis=1)
#dff = df.drop('text', axis=1)
#dff =dff.drop(df.columns[[0,1,2]], axis=1).copy()
#print(dff.head())



df = df.drop('stars', axis=1)

# Splitting the dataset into Training and testing
X_train, X_test, y_train, y_test = train_test_split(df['text'], y, test_size=0.33, random_state=2)

count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)
count_test = count_vectorizer.transform(X_test)

tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)
tfidf_train = tfidf_vectorizer.fit_transform(X_train)
tfidf_test = tfidf_vectorizer.transform(X_test)

tfidf_vectorizer.get_feature_names()[-10:]
count_vectorizer.get_feature_names()[:10]

count_df = pd.DataFrame(count_train.A, columns=count_vectorizer.get_feature_names())
tfidf_df = pd.DataFrame(tfidf_train.A, columns=tfidf_vectorizer.get_feature_names())
difference = set(count_df.columns) - set(tfidf_df.columns)

#print(count_df.equals(tfidf_df))
count_df.head()

tfidf_df.head()

#linear_clf = MultinomialNB()
linear_clf = PAC()


linear_clf.fit(tfidf_train, y_train)
pred = linear_clf.predict(tfidf_test)
score = metrics.accuracy_score(y_test, pred)
score = score * 100
print("Sentiment detection using PAC - accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred, labels=['positive', 'negative'])
#print(cm)
print(classification_report(y_test, pred))


Sentiment detection using PAC - accuracy:   93.955
             precision    recall  f1-score   support

   negative       0.93      0.94      0.93      3056
   positive       0.95      0.94      0.94      3544

avg / total       0.94      0.94      0.94      6600



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.passive_aggressive.PassiveAggressiveClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


In [0]:
linear_clf = MultinomialNB()
#linear_clf = PAC()


linear_clf.fit(tfidf_train, y_train)
pred = linear_clf.predict(tfidf_test)
score = metrics.accuracy_score(y_test, pred)
score = score * 100
print("Sentiment detection using MNB - accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred, labels=['positive', 'negative'])
#print(cm)
print(classification_report(y_test, pred))



Sentiment detection using MNB - accuracy:   92.470
             precision    recall  f1-score   support

   negative       0.92      0.92      0.92      3056
   positive       0.93      0.93      0.93      3544

avg / total       0.92      0.92      0.92      6600



### SENTIMENT DETECTION USING RNN

In [0]:
data = df4.copy()
data = data.sample(n=20000).copy()
data['Sentiment'] = [1 if x > 4 else 0 for x in data.stars]
from numpy.random import seed
seed(13)
from tensorflow import set_random_seed
set_random_seed(13)

X, y = (data['text'].values, data['Sentiment'].values)
tk = Tokenizer(lower = True)
tk.fit_on_texts(X)
X_seq = tk.texts_to_sequences(X)
X_pad = pad_sequences(X_seq, maxlen=100, padding='post')

X_train, X_test, y_train, y_test = train_test_split(X_pad, y, test_size = 0.20)

batch_size = 2000
X_train1 = X_train[batch_size:]
y_train1 = y_train[batch_size:]
X_valid = X_train[:batch_size]
y_valid = y_train[:batch_size]


vocabulary_size = len(tk.word_counts.keys())+1
max_words = 100
embedding_size = 32
model = Sequential()
model.add(Embedding(vocabulary_size, embedding_size, input_length=max_words))

model.add(LSTM(200))
model.add(Dense(1, activation='sigmoid'))
adam = Adam(lr=0.0001)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train1, y_train1 , validation_data=(X_valid, y_valid), batch_size=450, epochs=15, verbose=1)

Train on 14000 samples, validate on 2000 samples
Epoch 1/15
14000/14000 [==============================] - 12s 891us/step - loss: 0.6806 - acc: 0.5607 - val_loss: 0.6658 - val_acc: 0.6940
Epoch 2/15
14000/14000 [==============================] - 9s 673us/step - loss: 0.6225 - acc: 0.7108 - val_loss: 0.4215 - val_acc: 0.8270
Epoch 3/15
14000/14000 [==============================] - 9s 672us/step - loss: 0.2665 - acc: 0.8995 - val_loss: 0.2632 - val_acc: 0.9200
Epoch 4/15
14000/14000 [==============================] - 9s 672us/step - loss: 0.1126 - acc: 0.9616 - val_loss: 0.1822 - val_acc: 0.9380
Epoch 5/15
14000/14000 [==============================] - 9s 673us/step - loss: 0.0578 - acc: 0.9831 - val_loss: 0.1763 - val_acc: 0.9435
Epoch 6/15
14000/14000 [==============================] - 9s 673us/step - loss: 0.0335 - acc: 0.9919 - val_loss: 0.3305 - val_acc: 0.9185
Epoch 7/15
14000/14000 [==============================] - 9s 672us/step - loss: 0.0292 - acc: 0.9929 - val_loss: 0.2303 - 

In [0]:
scores = model.evaluate(X_test, y_test, verbose=0)
print("Test Accuracy :"+str(scores[1]*100))

Test Accuracy :91.975
